### ISSUE TITLE
ppx_tools port is wrongly versioned and not working on recent compilers

### ISSUE THREAD

**Issue by NathanReb** [dune-universe/opam-overlays#106]
The port of ppx_tools is versioned `7.0+dune` but there's not even a 7.0 version released. It also doesn't work on recent compilers whereas the upstream, released package seems to both build with dune and be compatible with OCaml 4.08 to 4.13.

We need to clean this port. We should look into which version it was built on top of and at the very least change the version here.

**Comment by NathanReb** [comment]
CC @Leonidas-from-XIV is this checked by the dune-universe linter ? Might be something worth adding otherwise. Dune ports should be based on an existing version upstream, eventually allowing a `+dev+dune` or some kind of marker if it's not exactly mapping to the version it's based on.

**Comment by Leonidas-from-XIV** [comment]
I also ran in this problem. It seemed to be based on a git commit past 6.1, but how 7.0 was chosen is unclear to me since at the time of writing. We could probably package a newer release of ppx_tools.

I don't quite know how to proceed with this port, since we can't really retract ports because someone might be depending on it. But it is also a headache if ppx_tools ever releases a 7.0.

It is not checked by the linter. I wonder if the OPAM libs can tell me the versions of a package from a specific opam repo, then it should be easy to check, that's a good point. I think we should add this as an improvement to the linter.

**Comment by NathanReb** [comment]
We can safely remove the `7.0+dune` version from opam-overlays, as long as we don't remove the corresponding release and tarball. We don't want to break existing lockfiles but we can remove the metadata so we don't generate such lockfiles anymore.

I think ppx_tools has been ported to dune since then, meaning we won't have to create a dune port for a future `7.0` so we should be safe here!
