### ISSUE TITLE
Maintenance status?

### ISSUE THREAD

**Issue by hannesm** [dune-universe/opam-overlays#87]
Hi,

I wanted to ask - since this contains various packages that now use dune in opam-repository (such as menhir), or are rather outdated (such as fmt) - whether this repository is actually taken care of? It also looks like the documentation could be revised with the duniverse -> opam-monorepo name change.

Thanks a lot and take care,

Hannes

**Comment by NathanReb** [comment]
This repo is indeed maintained. The fact that newer versions of the packages here have moved to dune doesn't make it less necessary for the existing dune ports to exist so that opam-monorepo users that have upper bounds on those can still use the tool. Existing dune ports don't require any extra maintenance so there really isn't a point removing them.

You're right that the README needs a refresh though. I'll look into this.

> or are rather outdated (such as fmt) 

Could you further explain what you mean by that? `fmt` does not seem outdated to me at all so I assume I'm misunderstanding something!

**Comment by hannesm** [comment]
> > or are rather outdated (such as fmt)
> Could you further explain what you mean by that? fmt does not seem outdated to me at all so I assume I'm misunderstanding something!

Browsing the current HEAD of this repository: https://github.com/dune-universe/opam-overlays/tree/51ff4352d4faf93a279d36c97ff510e27a49029f/packages/fmt has mt 0.8.8 and 0.8.9, https://opam.ocaml.org/packages/fmt/ carries a 0.8.10 and 0.9.0.

Same is true for bos (0.2.0 vs 0.2.1), rresult (0.6.0 vs 0.7.0), and potentially (likely) others... eventually some automation (a shell script) could help to report discover packages with newer versions in opam-repository.

**Comment by NathanReb** [comment]
The repo is maintained but we don't actively add dune ports before someone requests them. As you can imagine this is a rather time consuming task.

I'll look into porting the recent releases of those packages.

**Comment by NathanReb** [comment]
I'm closing this PR as I think the main question has been answered. Please feel free to open issues about specific packages that you need or outdated documentation if needed!

**Comment by hannesm** [comment]
Thanks for your quick reply. So these are one-off ports, that won't follow bugfixes of the upstream development? That's pretty sad to hear - but maybe worth to explicitly state in the README "if you want to update a package, please open an issue".
